---
title: "project 1"
author: "setareh gholami"
date: "2024-11-29"
output: html_document
---

my.id=(33)+20

set.seed(my.id)


```{r}
library(car)  
 
data(Salaries, package = "car")  
  
str(Salaries)  
head(Salaries)  

set.seed(123)  
ysr.service = sample(Salaries$salary, size = 53, replace = TRUE)  
  
miyangin = mean(ysr.service)  
miyane = median(ysr.service)  
variance = var(ysr.service)  
enheraf_meyar = sqrt(variance)  
damane_taghirat = IQR(ysr.service)  

miyangin
miyane
variance
enheraf_meyar
damane_taghirat
```

my.id=(30)+20
set.seed(my.id)

###charak sevom= 

#25 darsad data ha az an bozirg tar hastand

###charak dovom=

#50% data ha az an bozorg tar hastand

###charak aval=

#75% data ha az an bozorg tar hastand


```{r} 
set.seed(123)  
ysr.service = c(90000, 108200, 129600)[sample(1:3, 53, replace = TRUE)]  

ch123 = quantile(ysr.service, c(0.25, 0.5, 0.75))  

print(ch123)
```

my.id=(30)+20

set.seed(my.id)

###tarsim histogram

```{r}
library(car)  

data(Salaries, package = "car")  

hist(Salaries$salary,  
     main = 'Histogram',  
     xlab = 'Salary',  
     ylab = 'Faravani',  
     col = 'grey',  
     border = 'black',  
     breaks = 8 
)
```


```{r}
library(car)  
 
data(Salaries, package = "car")  
 
set.seed(123)  
sample_salaries <- sample(nrow(Salaries), size = 53, replace = TRUE)  
ysr.service <- Salaries$salary[sample_salaries]  
 
library(ggplot2)  
ggplot(Salaries, aes(x = rank)) +
  geom_bar() +  
  labs(title = "Distribution of Rank", x = "Rank", y = "tedad")  

ggplot(Salaries, aes(x = salary)) +  
  geom_histogram(binwidth = 10000) +  
  labs(title = "Distribution of Salaries", x = "Salary", y = "tedad")
```


my.id=(30)+20

set.seed(my.id)

###soal 3

```{r}
num=rnorm(100,mean=50,sd=10)
gerd=round(num,0)
m6=num[gerd%%6==0]
m6

```


my.id=(30)+20

set.seed(my.id)

###soal 4

```{r}  
library(car)  

data(Salaries, package = "car")  
 
f=function(x) {  
  n=nrow(Salaries)  
  sum((Salaries$salary / 1) / x)  
}  
x=1:nrow(Salaries)  
results=sapply(x, f)  
 
results

```



my.id=(30)+20

set.seed(my.id)

###mohasebe antegral


```{r}
f=function(x) {  
  1 + x^2  
}  

x=integrate(f, 1/2, 3)  
print(x)  
  
ff=function(y) {  
  3 + y^2 - 1  
}  

y=integrate(ff, 3, 5)  
r=y$value  
r


```


my.id=(30)+20

set.seed(my.id)

###matrix

```{r}
 
b=c(1, 2, 4, 6, 1, 3, 9, 5, 3)  

a=matrix(b, nrow = 3, byrow = TRUE)  

determinant=det(a)  
print(determinant)  

inverse=solve(a)  
print(inverse)  

diagonal_elements=diag(a)  

reversed_diagonal=rev(diagonal_elements)  
 
a[row(a) == col(a)] = 0  
a
```








